### ISSUE TITLE
Bring the SciGlass database online

### ISSUE THREAD

**Issue by Lexachoc** [epam/SciGlass#4]
As the SciGlass database is one of the largest glass databases in the world, its importance cannot be overlooked.

I would like to advertise my small project that brings SciGlass online, namely **[SciGlass Next](https://sciglass.uni-jena.de/)**, which uses the data published in this repo under the ODC Open Database Licence (ODbL).

**Beta Testing**
The **[SciGlass Next](https://sciglass.uni-jena.de/)** is currently in beta testing. Registration via the institutional e-mail is required for access.

**Feedbacks**
There are many wrong values in the published data, with 422K+ entries, of course it's not 100% perfect, so we need your feedback to make it better! And I will do my best to correct mistakes and improve it.

**Looking for collaboration**
Since the predicted property data is not published, we are looking for collaboration on glass prediction models that can be integrated into SciGlass Next (Python backend). 

Please contact me if you would like to collaborate on the glass prediction models.

**Roadmap for the main features:**
- [x] Search for tables (Common Query in SciGlass)
- [x] Search for glasses (Experimental Data in SciGlass)
- [x] Predicted Properties (First integration: [GlassNet](https://github.com/drcassar/glasspy). Also looking for more predictive models, please contact us for collaboration/integration.)
- [x] Table by number
- [x] Patent Index
- [x] Trademark Index
- [x] Author Index
- [x] Subject Index
- [x] Glass Formation
- [x] Spectral Index
- [x] Property Diagram (new since SciGlass Next v0.4.0)
- [ ] Unit Conversion (partially supported since v0.5.0)
- [X] ML Prediction (First integration: [GlassNet](https://github.com/drcassar/glasspy))

New features such as ML integration are planned in the near future, stay tuned!

**Some screenshots:**

![Image](https://github.com/user-attachments/assets/1cafc036-8c8b-47b5-a5cd-3160b14c7bbb)

![Image](https://github.com/user-attachments/assets/b9793794-07d5-4e45-b1e2-aa7165a3ed9c)

![Image](https://github.com/user-attachments/assets/a77378bd-7551-402a-95b1-287452a05594)

![Image](https://github.com/user-attachments/assets/70086b15-2859-4dcd-8ce1-1167823f5f67)

![Image](https://github.com/user-attachments/assets/acce75d0-597e-489a-a3ee-cb430322b290)

![Image](https://github.com/user-attachments/assets/f77f72b5-5dd6-43b0-98e9-f1d4e9345d8b)

![Image](https://github.com/user-attachments/assets/519beba2-8cad-4eb1-ab0d-5498b8fab664)

![Image](https://github.com/user-attachments/assets/5d071545-3d54-4f97-ae38-cf3cf8c232b6)

Support both light/dark theme as well.

![Image](https://github.com/user-attachments/assets/8a78c730-e0e9-4b24-a32c-30825a16d58a)

Property Predictor introduced in 10.06.2024:

![Image](https://github.com/user-attachments/assets/2409c213-f833-4ac1-8868-702f0ccc1e7b)

Property Diagram introduced in 26.07.2024:

![Image](https://github.com/user-attachments/assets/53618e27-654f-410d-82b0-dd3482a40db5)

API Access:

![Image](https://github.com/user-attachments/assets/7de8c2ad-db39-472a-97a6-b8236e56cee9)

**In memory of Oleg Mazurin – Russian glass scientist and SciGlass founder**
https://ceramics.org/person/oleg-vsevolodovich-mazurin/

**Comment by jakeogh** [comment]
Looks excellent. I created an account with my work address @arizona.edu, but have not received the verification email.

**Comment by Lexachoc** [comment]
Hi @jakeogh 

Our university's mail server could have a problem at that exact moment, or the Arizona mail server could have blocked it. I'm not sure.

I have now given you access. You should now be able to access the database.

Also I sent you a welcome e-mail. Could you please check if you received it or not?

**Comment by jakeogh** [comment]
Got it! I'm in TY!!!
